export type QuoteCategory =
  | "stoicism"
  | "discipline"
  | "identity"
  | "cravings"
  | "consequences"
  | "courage"
  | "future"
  | "self-respect"
  | "freedom"
  | "one-day"
  | "short";

export interface Quote {
  text: string;
  author?: string;
  category: QuoteCategory;
}

export const QUOTE_CATEGORY_LABELS: Record<QuoteCategory, string> = {
  stoicism: "Stoicism",
  discipline: "Discipline",
  identity: "Identity",
  cravings: "Cravings",
  consequences: "Reality check",
  courage: "Courage",
  future: "Future self",
  "self-respect": "Self-respect",
  freedom: "Freedom",
  "one-day": "One day at a time",
  short: "Daily reminder",
};

export const QUOTES: Quote[] = [
  { text: "You have power over your mind—not outside events.", author: "Marcus Aurelius", category: "stoicism" },
  { text: "No man is free who is not master of himself.", author: "Epictetus", category: "stoicism" },
  { text: "The obstacle is the way.", author: "Marcus Aurelius", category: "stoicism" },
  { text: "It is not things that disturb us, but our judgments about things.", author: "Epictetus", category: "stoicism" },
  { text: "I don't need to win against the craving. I only need to refuse it.", category: "stoicism" },
  { text: "The craving is temporary. My decision is permanent.", category: "stoicism" },
  { text: "Feelings are not commands.", category: "stoicism" },
  { text: "I don't negotiate with cravings.", category: "stoicism" },
  { text: "I can be uncomfortable without doing something about it.", category: "stoicism" },
  { text: "Discipline is choosing between what you want now and what you want most.", category: "discipline" },
  { text: "You don't rise to the level of your goals. You fall to the level of your systems.", author: "James Clear", category: "discipline" },
  { text: "Every time I say no, I become stronger at saying no.", category: "discipline" },
  { text: "Do what needs to be done, especially when you don't feel like doing it.", category: "discipline" },
  { text: "The hardest part is deciding. You already decided.", category: "discipline" },
  { text: "Don't negotiate with the version of yourself that wants to relapse.", category: "discipline" },
  { text: "I don't drink. I don't use. That's who I am.", category: "identity" },
  { text: "This is not deprivation. This is who I am.", category: "identity" },
  { text: "I don't need to resist temptation when temptation isn't part of my identity.", category: "identity" },
  { text: "I am building a person I don't need to escape from.", category: "identity" },
  { text: "Every sober day is evidence of who I'm becoming.", category: "identity" },
  { text: "I don't want sobriety. I want the life sobriety gives me.", category: "identity" },
  { text: "Become the person who doesn't need the substance.", category: "identity" },
  { text: "I am not someone who uses to cope.", category: "identity" },
  { text: "A craving is a wave. I don't have to surf it.", category: "cravings" },
  { text: "This feeling will pass whether I use or not.", category: "cravings" },
  { text: "Wait 20 minutes. Decide later.", category: "cravings" },
  { text: "I don't have to solve my whole life tonight.", category: "cravings" },
  { text: "The craving is asking for relief, not the substance.", category: "cravings" },
  { text: "Urges peak, then fall. I just have to stay.", category: "cravings" },
  { text: "This is a craving, not a command.", category: "cravings" },
  { text: "I can have an urge without acting on it.", category: "cravings" },
  { text: "Let the craving exist. I don't have to feed it.", category: "cravings" },
  { text: "You don't have to do anything just because you feel something.", category: "cravings" },
  { text: "Remember the whole story, not just the good part.", category: "consequences" },
  { text: "Don't trade tomorrow's peace for tonight's relief.", category: "consequences" },
  { text: "The first drink isn't the whole story. Remember what comes after.", category: "consequences" },
  { text: "Play the tape forward.", category: "consequences" },
  { text: "You already know where this road goes.", category: "consequences" },
  { text: "Remember why you stopped.", category: "consequences" },
  { text: "Don't let your brain romanticize what your life taught you to leave behind.", category: "consequences" },
  { text: "You are remembering the high. Remember the aftermath too.", category: "consequences" },
  { text: "Courage is staying when you want to escape.", category: "courage" },
  { text: "I can survive this feeling without anesthetizing it.", category: "courage" },
  { text: "I don't need to numb pain to prove I can handle it.", category: "courage" },
  { text: "Let it hurt. Let it pass. Don't run.", category: "courage" },
  { text: "Discomfort is not an emergency.", category: "courage" },
  { text: "You don't need to escape every uncomfortable feeling.", category: "courage" },
  { text: "This moment is hard. That doesn't mean you need to make it worse.", category: "courage" },
  { text: "Feel it. Don't feed it.", category: "courage" },
  { text: "Every sober decision is a vote for my future self.", category: "future" },
  { text: "I'm not giving something up. I'm getting myself back.", category: "future" },
  { text: "Protect the life you're building.", category: "future" },
  { text: "Six months from now, you'll be grateful you said no today.", category: "future" },
  { text: "Become someone your future self can trust.", category: "future" },
  { text: "Your future self is watching what you choose today.", category: "future" },
  { text: "Build a life you don't need to escape from.", category: "future" },
  { text: "Don't sacrifice your future for a temporary feeling.", category: "future" },
  { text: "Keep the promise you made when you were clear-minded.", category: "self-respect" },
  { text: "Self-respect is built by keeping promises to yourself.", category: "self-respect" },
  { text: "I don't betray tomorrow's version of me for today's craving.", category: "self-respect" },
  { text: "Every time I keep my word to myself, I trust myself more.", category: "self-respect" },
  { text: "I deserve to wake up proud of myself.", category: "self-respect" },
  { text: "Keep your word to yourself.", category: "self-respect" },
  { text: "You said you were done. Be the person who keeps that promise.", category: "self-respect" },
  { text: "Sobriety is freedom from needing something to feel okay.", category: "freedom" },
  { text: "I don't want to be controlled by something I put in my own body.", category: "freedom" },
  { text: "Freedom is being able to choose without craving choosing for me.", category: "freedom" },
  { text: "Nothing owns me.", category: "freedom" },
  { text: "I want my life back.", category: "freedom" },
  { text: "I am free to feel everything without needing to numb anything.", category: "freedom" },
  { text: "The goal isn't to resist forever. The goal is to become free.", category: "freedom" },
  { text: "Just today.", category: "one-day" },
  { text: "I don't need to stay sober forever today. I just need to stay sober today.", category: "one-day" },
  { text: "Win today. Tomorrow can wait.", category: "one-day" },
  { text: "One craving. One decision. One day.", category: "one-day" },
  { text: "Don't worry about 1,000 days. Protect this one.", category: "one-day" },
  { text: "Today is the only day I have to win.", category: "one-day" },
  { text: "Get through this moment. Then the next.", category: "one-day" },
  { text: "You don't need to figure out forever. Just don't use today.", category: "one-day" },
  { text: "This too shall pass.", category: "short" },
  { text: "Don't negotiate.", category: "short" },
  { text: "Protect your streak.", category: "short" },
  { text: "Protect your future.", category: "short" },
  { text: "Remember why.", category: "short" },
  { text: "Stay.", category: "short" },
  { text: "You already know.", category: "short" },
  { text: "Choose yourself.", category: "short" },
  { text: "Don't trade tomorrow for tonight.", category: "short" },
  { text: "You are stronger than the urge.", category: "short" },
  { text: "The urge is temporary.", category: "short" },
  { text: "Keep your promise.", category: "short" },
  { text: "Be free.", category: "short" },
  { text: "Become who you said you'd become.", category: "short" },
  { text: "You don't need it.", category: "short" },
  { text: "Let the wave pass.", category: "short" },
  { text: "You don't have to obey every feeling you have.", category: "short" },
];
